version: '3.7'
services:
  app:
    build: ./docker
    ports:
      - 80:80
    volumes:
      - type: bind
        source: "./app"
        target: "/var/www/app"
      - ./apache2.conf:/etc/apache2/apache2.conf
    working_dir: /var/www/app
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./volumes:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
